server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://10.200.0.251/dmatch?useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: none
#  redis:
#    host: 127.0.0.1
#    port: 6379
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB